-- 코드를 입력하세요
# SELECT A.BOOK_ID
#       , A.CATEGORY
#       , A.AUTHOR_ID
#       , C.AUTHOR_NAME
#       , B.SALES * A.PRICE AS TOTAL_SALES
# FROM BOOK A
# INNER JOIN (SELECT BOOK_ID, SALES FROM BOOK_SALES WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-01') B
#             ON A.BOOK_ID = B.BOOK_ID
# LEFT OUTER JOIN AUTHOR C
#                 ON A.AUTHOR_ID = C.AUTHOR_ID
# ORDER BY AUTHOR_ID ASC, CATEGORY DESC
WITH BOOK_SALE AS (
SELECT A.BOOK_ID
      , A.CATEGORY
      , A.AUTHOR_ID
      , B.SALES * A.PRICE AS TOTAL_SALES
FROM BOOK A
INNER JOIN (SELECT BOOK_ID, SALES FROM BOOK_SALES WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-01') B
            ON A.BOOK_ID = B.BOOK_ID),

BOOK_SALES_GR AS (
SELECT AUTHOR_ID
      , CATEGORY
      , SUM(TOTAL_SALES) AS TOTAL_SALES
FROM BOOK_SALE
GROUP BY AUTHOR_ID, CATEGORY
)
            
SELECT A.AUTHOR_ID
      , B.AUTHOR_NAME
      , A.CATEGORY
      , A.TOTAL_SALES
FROM BOOK_SALES_GR A
LEFT OUTER JOIN AUTHOR B
                ON A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC
