-- 코드를 입력하세요
WITH MILK AS
(SELECT CART_ID, NAME
FROM CART_PRODUCTS
WHERE NAME = 'Milk'
),
YOGURT AS 
(SELECT CART_ID, NAME
FROM CART_PRODUCTS
WHERE NAME = 'Yogurt'
)

SELECT DISTINCT A.CART_ID
FROM CART_PRODUCTS A
LEFT OUTER JOIN MILK B
            ON A.CART_ID = B.CART_ID
LEFT OUTER JOIN YOGURT C
            ON A.CART_ID = C.CART_ID
WHERE B.NAME IS NOT NULL
      AND C.NAME IS NOT NULL
ORDER BY A.CART_ID      