-- 코드를 작성해주세요
WITH FIRST_ID AS (
SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL
),

SECOND_ID AS (
SELECT A.ID
FROM ECOLI_DATA A
INNER JOIN FIRST_ID B
            ON A.PARENT_ID = B.ID
)

SELECT A.ID
FROM ECOLI_DATA A
INNER JOIN SECOND_ID B
            ON A.PARENT_ID = B.ID
ORDER BY A.ID ASC