# -- 코드를 작성해주세요
# SELECT COUNT(*)
# FROM ECOLI_DATA
# GROUP BY PARENT_ID
# HAVING PARENT_ID = ID

SELECT A.ID
      , IFNULL(B.CHILD_COUNT,0) AS CHILD_COUNT
FROM ECOLI_DATA A
LEFT OUTER JOIN (SELECT PARENT_ID
                        , COUNT(*) AS CHILD_COUNT
                 FROM ECOLI_DATA
                 GROUP BY PARENT_ID) B
ON A.ID = B.PARENT_ID
ORDER BY ID ASC

