-- 코드를 입력하세요
WITH ONLINE AS (
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE
      , PRODUCT_ID
      , USER_ID
      , SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'
),


OFFLINE AS (
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE
      , PRODUCT_ID
      , NULL AS USER_ID
      , SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'
)


SELECT *
FROM ONLINE
UNION ALL
SELECT *
FROM OFFLINE
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID