WITH TMP01 AS (
SELECT CAR_ID
      , CAR_TYPE
      , DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_ID NOT IN (SELECT DISTINCT CAR_ID
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                     WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') < '2022-12-01'
                           AND DATE_FORMAT(END_DATE, '%Y-%m-%d') > '2022-11-01')
     AND CAR_TYPE IN ('SUV', '세단')
),

TMP02 AS (
SELECT A.CAR_ID
      , A.CAR_TYPE
      , ROUND(A.DAILY_FEE * (1 - B.DISCOUNT_RATE / 100) * 30) AS FEE
FROM TMP01 A
LEFT OUTER JOIN (SELECT CAR_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상') B
                ON A.CAR_TYPE = B.CAR_TYPE
)


SELECT *
FROM TMP02
WHERE FEE >= 500000
      AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
     




