-- 코드를 작성해주세요
WITH SIZE_RANK AS(
SELECT ID
        , SIZE_OF_COLONY
        , PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_PERCENT_RANK
FROM ECOLI_DATA
ORDER BY ID ASC)

SELECT A.ID
    , CASE WHEN B.SIZE_PERCENT_RANK >= 0.75 THEN 'LOW'
           WHEN B.SIZE_PERCENT_RANK >= 0.5 THEN 'MEDIUM'
           WHEN B.SIZE_PERCENT_RANK >= 0.25 THEN 'HIGH'
           ELSE 'CRITICAL' END AS COLONY_NAME
FROM ECOLI_DATA A
LEFT OUTER JOIN SIZE_RANK B
                ON A.ID = B.ID
