-- 코드를 입력하세요
SELECT A.USER_ID
     , A.NICKNAME
     , CONCAT(A.CITY, ' ', A.STREET_ADDRESS1, ' ', A.STREET_ADDRESS2) AS 전체주소
     , CONCAT(SUBSTR(A.TLNO, 1, 3), '-', SUBSTR(A.TLNO, 4, 4), '-', SUBSTR(A.TLNO, 8, 4))  AS 전화번호
FROM USED_GOODS_USER A
INNER JOIN (SELECT WRITER_ID
      , COUNT(*) AS CNT
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING CNT >= 3) B
            ON A.USER_ID = B.WRITER_ID
ORDER BY USER_ID DESC
