-- 코드를 입력하세요
# SELECT A.CAR_ID
#       , A.START_DATE
#       , A.END_DATE
#       , CASE WHEN '2022-10-16' BETWEEN A.START_DATE AND A.END_DATE THEN '대여중'
#               ELSE '대여가능' END AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
# INNER JOIN (SELECT CAR_ID, MAX(HISTORY_ID) AS MAX_HISTORY_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY GROUP BY CAR_ID) B
#             ON A.CAR_ID = B.CAR_ID
#                 AND A.HISTORY_ID = B.MAX_HISTORY_ID
# ORDER BY A.CAR_ID DESC



# SELECT CAR_ID
#       , START_DATE
#       , END_DATE
#       , MAX(CASE WHEN CAR_ID IN (SELECT CAR_ID
#                              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#                              WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE)
#                              THEN '대여중'
#              ELSE '대여가능' END) AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# ORDER BY CAR_ID DESC



SELECT DISTINCT CAR_ID,
CASE
    WHEN MAX('2022-10-16' BETWEEN START_DATE AND END_DATE) = 1 THEN '대여중'
    ELSE '대여 가능'
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC