-- 코드를 입력하세요
SELECT A.PRODUCT_ID
      , A.PRODUCT_NAME
      , A.PRICE * B.SUM_AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT A
INNER JOIN (SELECT PRODUCT_ID
                  , SUM(AMOUNT) AS SUM_AMOUNT
            FROM FOOD_ORDER
            WHERE DATE_FORMAT(PRODUCE_DATE, '%y%m') = '2205'
            GROUP BY PRODUCT_ID) B
            ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC

