-- 코드를 입력하세요

WITH TMP01 AS (
SELECT A.HISTORY_ID
      , A.CAR_ID
      , B.DAILY_FEE
      , DATEDIFF(A.END_DATE, A.START_DATE) + 1 AS DURATION
      , CASE WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 90 THEN '90일 이상'
             WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 30 THEN '30일 이상'
             WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 7 THEN '7일 이상'
             ELSE 'NONE' END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
INNER JOIN (SELECT CAR_ID, DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE = '트럭') B
            ON A.CAR_ID = B.CAR_ID
), TMP02 AS (
SELECT A.HISTORY_ID
      , A.CAR_ID
      , A.DAILY_FEE
      , A.DURATION
      , A.DURATION_TYPE
      , CASE WHEN B.DISCOUNT_RATE IS NULL THEN 0
             ELSE B.DISCOUNT_RATE END AS DISCOUNT_RATE
FROM TMP01 A
LEFT OUTER JOIN (SELECT DURATION_TYPE
                       , DISCOUNT_RATE
                 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                 WHERE CAR_TYPE = '트럭') B
                 ON A.DURATION_TYPE = B.DURATION_TYPE)
                 
SELECT HISTORY_ID
      , ROUND(DAILY_FEE * (1 - DISCOUNT_RATE / 100) * DURATION) AS FEE
FROM TMP02
ORDER BY FEE DESC, HISTORY_ID DESC



                 