-- 코드를 입력하세요
WITH RECURSIVE CTE AS (
SELECT 0 AS HOUR
UNION ALL
SELECT HOUR + 1 FROM CTE
WHERE HOUR < 23)

SELECT A.HOUR
      , IFNULL(B.COUNT,0) AS COUNT
FROM CTE A
LEFT OUTER JOIN (SELECT HOUR(DATETIME) AS HOUR
                       , COUNT(*) AS COUNT
                 FROM ANIMAL_OUTS
                 GROUP BY HOUR(DATETIME)) B
                 ON A.HOUR = B.HOUR
ORDER BY A.HOUR