-- 코드를 작성해주세요
SELECT DISTINCT B.ID
      , B.EMAIL
      , B.FIRST_NAME
      , B.LAST_NAME
FROM SKILLCODES A
INNER JOIN DEVELOPERS B
            ON A.CODE & B.SKILL_CODE
WHERE A.CATEGORY = 'Front End'
ORDER BY B.ID ASC