WITH MAX_MEMBER AS (
SELECT MEMBER_ID
      , COUNT(*) AS CNT
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY CNT DESC
LIMIT 1
)

SELECT C.MEMBER_NAME
      , A.REVIEW_TEXT
      , DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW A
INNER JOIN MAX_MEMBER B
          ON A.MEMBER_ID = B.MEMBER_ID
INNER JOIN MEMBER_PROFILE C
          ON A.MEMBER_ID = C.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC