SELECT DATE_FORMAT(A.START_DATE, '%m') AS MONTH
    , A.CAR_ID
    , COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
INNER JOIN (SELECT CAR_ID
    , COUNT(*) AS CNT
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY CAR_ID
HAVING CNT >= 5) B
    ON A.CAR_ID = B.CAR_ID
GROUP BY MONTH, A.CAR_ID
HAVING RECORDS != 0
        AND MONTH IN ('08', '09', '10')
ORDER BY MONTH ASC, CAR_ID DESC