SELECT A.ID
      , C.FISH_NAME
      , B.LENGTH
FROM FISH_INFO A
INNER JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO GROUP BY FISH_TYPE) B
                ON A.FISH_TYPE = B.FISH_TYPE
                   AND A.LENGTH = B.LENGTH
LEFT OUTER JOIN FISH_NAME_INFO C
               ON A.FISH_TYPE = C.FISH_TYPE
ORDER BY A.ID ASC
